s/@aacute;/á/g
s/@Aacute;/Á/g
s/@agrave;/à/g
s/@Agrave;/À/g
s/@eacute;/é/g
s/@Eacute;/É/g
s/@egrave;/è/g
s/@Egrave;/È/g
s/@iacute;/í/g
s/@Iacute;/Í/g
s/@iuml;/ï/g
s/@Iuml;/Ï/g
s/@oacute;/ó/g
s/@Oacute;/Ó/g
s/@ograve;/ò/g
s/@Ograve;/Ò/g
s/@uacute;/ú/g
s/@Uacute;/Ú/g
s/@uuml;/ü/g
s/@Uuml;/Ü/g
s/@ccedilla;/ç/g
s/@Ccedilla;/Ç/g
s/@ntilde;/ñ/g
s/@Ntilde;/Ñ/g
s/@middledot;/·/g
s/@#319;/L·/g
s/@#320;/l·/g
